### ISSUE TITLE
Check WinRM configuration for valid configuration for IPv4 and IPv6

### ISSUE THREAD

**Issue by flobroeder** [fbprogmbh/SystemValidator#17]
WInRM need a valid configuration for IPv4 AND IPv6 in case IPv6 is not disabled...
So please check for at least a "*" on both protocols....

The following configuraiton was applied and lead to severe WinRM errors:

![image](https://github.com/fbprogmbh/SystemValidator/assets/23223285/ee295ee4-0f53-4aff-9847-023fd56e2444)

Root cause:
* IPv4 was configured correctly (* was applied)
* IPv6 was not configured correctly (nothing was configured)

This resulted in errrors.

**Comment by TuemmlerKelch** [comment]
@SteffenWinternheimer 
Please correct and test on your device. This has to be complaint on your system.
![image](https://github.com/fbprogmbh/SystemValidator/assets/68649859/c815c968-4f33-4823-a3d9-757cb544e18a)

**Comment by TuemmlerKelch** [comment]
Filters are now checked and displayed correctly
